server:
  port: 8081
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/card_server
    username: springuser
    password: rodkotkrv82)R
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
security.jwt.secret: otherpeopledontknowit


