server:
  port: 8082
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/card_server
    username: springuser
    password: rodkotkrv82)R
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html